name: Deploy speedlify instance to GitHub Pages

on:
  push:
    branches:
      live

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci

      - name: Cache Speedlify results
        id: cache-speedlify-results
        uses: actions/cache@v3
        with:
          path: _data/results
          key: ${{ runner.os }}-primes

      - name: Run lighthouse
        run: npm run test-pages

      - name: Build for production
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: _site
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
